### ISSUE TITLE
Research a UI Library

### ISSUE THREAD

**Issue by PrestonMonteWest** [PrestonMonteWest/managerio#8]
Possible candidates:
- Wix: https://github.com/wix/react-native-ui-lib
- NativeBase: https://github.com/GeekyAnts/nativebase
- shoutem: https://shoutem.github.io/docs/ui-toolkit/introduction
- honorable mention - https://github.com/FaridSafi/react-native-gifted-chat

**Comment by joeycuty** [comment]
@PrestonMonteWest did some digging and my vote is still WIX. the gifted chat lib may be useful for chat. lmk if you have any prefs / thoughts
